version: '3.8'

services:
  app:
    container_name: app-ted
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres-shared:5432/api-transferegov
      - REDIS_URL=redis://redis-shared:6379/0
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-ted.rule=Host(`api.kingdomsys.com`)&&PathPrefix(`/api-ted`)"
      - "traefik.http.routers.api-ted.entrypoints=websecure"
      - "traefik.http.routers.api-ted.tls=true"
      - "traefik.http.routers.api-ted.tls.certresolver=letsencrypt"
      - "traefik.http.services.api-ted.loadbalancer.server.port=8000"
       # - "traefik.http.middlewares.api-ted-strip.stripprefix.prefixes=/api-ted"
       # - "traefik.http.routers.api-ted.middlewares=api-ted-strip"

       # Adicione esta configuração para WebSockets
      - "traefik.http.routers.api-ted-ws.rule=Host(`api.kingdomsys.com`) && PathPrefix(`/api-ted/ws`)"
      - "traefik.http.routers.api-ted-ws.entrypoints=websecure"
      - "traefik.http.routers.api-ted-ws.tls=true"
      - "traefik.http.routers.api-ted-ws.tls.certresolver=letsencrypt"
      - "traefik.http.routers.api-ted-ws.service=api-ted"

networks:
  default:
    name: web-apps
    external: true
